# Generated by Django 6.0.7 on 2026-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.FloatField(default=180.0)),
                ('pressure', models.FloatField(default=1013.2)),
                ('maxtemp', models.FloatField(default=30.0)),
                ('temparature', models.FloatField(default=25.5)),
                ('mintemp', models.FloatField(default=21.0)),
                ('dewpoint', models.FloatField(default=22.0)),
                ('humidity', models.FloatField(default=80.0)),
                ('cloud', models.FloatField(default=65.0)),
                ('sunshine', models.FloatField(default=5.0)),
                ('winddirection', models.FloatField(default=180.0)),
                ('windspeed', models.FloatField(default=12.5)),
                ('prediction', models.IntegerField(default=0)),
                ('will_rain', models.BooleanField(default=False)),
                ('rain_probability', models.FloatField(default=0.0)),
                ('no_rain_probability', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='xgboost', max_length=50)),
                ('model_display_name', models.CharField(default='XGBoost ML Model', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
